package de.xyzerstudios.moneymanager.utils.currency;

import java.util.ArrayList;
import java.util.HashMap;

public class Currencies {

    private static HashMap<String, String> isoToName; // Key: EUR Value: Euro
    private static HashMap<String, String> isoToUnicode; // Key: EUR Value: €
    private static ArrayList<String> isoCodes;
    private static ArrayList<String> isoCodesOfCurrenciesUsedMost;

    public static void init() {
        isoToName = new HashMap<>();
        isoToUnicode = new HashMap<>();
        isoCodes = new ArrayList<>();
        isoCodesOfCurrenciesUsedMost = new ArrayList<>();
        addCurrenciesToIsoToName();
        addCurrenciesToIsoToUnicode();
        addCurrenciesToIsoCodes();
        addCurrenciesToIsoCodesUM();
    }

    public static HashMap<String, String> getIsoToName() {
        return isoToName;
    }

    public static HashMap<String, String> getIsoToUnicode() {
        return isoToUnicode;
    }

    public static ArrayList<String> getIsoCodes() {
        return isoCodes;
    }

    public static ArrayList<String> getIsoCodesOfCurrenciesUsedMost() {
        return isoCodesOfCurrenciesUsedMost;
    }

    private static void addCurrenciesToIsoCodesUM() {
        try {
            isoCodesOfCurrenciesUsedMost.add("USD");
            isoCodesOfCurrenciesUsedMost.add("EUR");
            isoCodesOfCurrenciesUsedMost.add("JPY");
            isoCodesOfCurrenciesUsedMost.add("GBP");
            isoCodesOfCurrenciesUsedMost.add("INR");
            isoCodesOfCurrenciesUsedMost.add("AUD");
            isoCodesOfCurrenciesUsedMost.add("CAD");
            isoCodesOfCurrenciesUsedMost.add("CHF");
            isoCodesOfCurrenciesUsedMost.add("CNY");
            isoCodesOfCurrenciesUsedMost.add("HKD");
            isoCodesOfCurrenciesUsedMost.add("NZD");
            isoCodesOfCurrenciesUsedMost.add("IDR");
        } catch (Exception e) {
            throw new ClassCastException("Must initialize \"Currencies\" with .init() before usage.");
        }
    }

    private static void addCurrenciesToIsoToUnicode() { //TODO: Add Unicodes
        try {
            isoToUnicode.put("AFN", "؋");
            isoToUnicode.put("ARS", "$");
            isoToUnicode.put("AWG", "ƒ");
            isoToUnicode.put("AUD", "$");
            isoToUnicode.put("AZN", "₼");
            isoToUnicode.put("BSD", "$");
            isoToUnicode.put("BBD", "$");
            isoToUnicode.put("BYR", "p.");
            isoToUnicode.put("BZD", "BZ$");
            isoToUnicode.put("BMD", "$");
            isoToUnicode.put("BOB", "$b");
            isoToUnicode.put("BAM", "KM");
            isoToUnicode.put("BWP", "P");
            isoToUnicode.put("BGN", "лв");
            isoToUnicode.put("BRL", "R$");
            isoToUnicode.put("BND", "$");
            isoToUnicode.put("KHR", "៛");
            isoToUnicode.put("CAD", "$");
            isoToUnicode.put("KYD", "$");
            isoToUnicode.put("CLP", "$");
            isoToUnicode.put("CNY", "¥");
            isoToUnicode.put("COP", "$");
            isoToUnicode.put("CRC", "₡");
            isoToUnicode.put("HRK", "kn");
            isoToUnicode.put("CUP", "₱");
            isoToUnicode.put("CZK", "Kč");
            isoToUnicode.put("DKK", "kr");
            isoToUnicode.put("DOP", "RD$");
            isoToUnicode.put("EGP", "£");
            isoToUnicode.put("SVC", "$");
            isoToUnicode.put("EEK", "kr");
            isoToUnicode.put("EUR", "€");
            isoToUnicode.put("FKP", "£");
            isoToUnicode.put("FJD", "$");
            isoToUnicode.put("GEL", "₾");
            isoToUnicode.put("GHC", "¢");
            isoToUnicode.put("GIP", "£");
            isoToUnicode.put("GTQ", "Q");
            isoToUnicode.put("GGP", "£");
            isoToUnicode.put("GYD", "$");
            isoToUnicode.put("HNL", "L");
            isoToUnicode.put("HKD", "$");
            isoToUnicode.put("HUF", "Ft");
            isoToUnicode.put("ISK", "kr");
            isoToUnicode.put("INR", "₹");
            isoToUnicode.put("IDR", "Rp");
            isoToUnicode.put("IRR", "﷼");
            isoToUnicode.put("IMP", "£");
            isoToUnicode.put("ILS", "₪");
            isoToUnicode.put("JMD", "J$");
            isoToUnicode.put("JPY", "¥");
            isoToUnicode.put("JEP", "£");
            isoToUnicode.put("KZT", "лв");
            isoToUnicode.put("KPW", "₩");
            isoToUnicode.put("KRW", "₩");
            isoToUnicode.put("KGS", "лв");
            isoToUnicode.put("LAK", "₭");
            isoToUnicode.put("LVL", "Ls");
            isoToUnicode.put("LBP", "£");
            isoToUnicode.put("LRD", "$");
            isoToUnicode.put("LTL", "Lt");
            isoToUnicode.put("MKD", "ден");
            isoToUnicode.put("MYR", "RM");
            isoToUnicode.put("MUR", "₨");
            isoToUnicode.put("MXN", "$");
            isoToUnicode.put("MNT", "₮");
            isoToUnicode.put("MZN", "MT");
            isoToUnicode.put("NAD", "$");
            isoToUnicode.put("NPR", "₨");
            isoToUnicode.put("ANG", "ƒ");
            isoToUnicode.put("NZD", "$");
            isoToUnicode.put("NIO", "C$");
            isoToUnicode.put("NGN", "₦");
            isoToUnicode.put("NOK", "kr");
            isoToUnicode.put("OMR", "﷼");
            isoToUnicode.put("PKR", "₨");
            isoToUnicode.put("PAB", "B/.");
            isoToUnicode.put("PYG", "Gs");
            isoToUnicode.put("PEN", "S/.");
            isoToUnicode.put("PHP", "₱");
            isoToUnicode.put("PLN", "zł");
            isoToUnicode.put("QAR", "﷼");
            isoToUnicode.put("RON", "lei");
            isoToUnicode.put("RUB", "₽");
            isoToUnicode.put("SHP", "£");
            isoToUnicode.put("SAR", "﷼");
            isoToUnicode.put("RSD", "Дин.");
            isoToUnicode.put("SCR", "₨");
            isoToUnicode.put("SGD", "$");
            isoToUnicode.put("SBD", "$");
            isoToUnicode.put("SOS", "S");
            isoToUnicode.put("ZAR", "R");
            isoToUnicode.put("LKR", "₨");
            isoToUnicode.put("SEK", "kr");
            isoToUnicode.put("SRD", "$");
            isoToUnicode.put("SYP", "£");
            isoToUnicode.put("TWD", "NT$");
            isoToUnicode.put("THB", "฿");
            isoToUnicode.put("TTD", "TT$");
            isoToUnicode.put("TRL", "₺");
            isoToUnicode.put("TVD", "$");
            isoToUnicode.put("UAH", "₴");
            isoToUnicode.put("GBP", "£");
            isoToUnicode.put("USD", "$");
            isoToUnicode.put("UYU", "$U");
            isoToUnicode.put("UZS", "лв");
            isoToUnicode.put("VEF", "Bs");
            isoToUnicode.put("VND", "₫");
            isoToUnicode.put("YER", "﷼");
            isoToUnicode.put("ZWD", "Z$");
        } catch (Exception e) {
            throw new ClassCastException("Must initialize \"Currencies\" with .init() before usage.");
        }
    }

    private static void addCurrenciesToIsoCodes() {
        try {
            isoCodes.add("AFN");
            isoCodes.add("FJD");
            isoCodes.add("MXN");
            isoCodes.add("STD");
            isoCodes.add("SCR");
            isoCodes.add("CDF");
            isoCodes.add("BBD");
            isoCodes.add("GTQ");
            isoCodes.add("CLP");
            isoCodes.add("HNL");
            isoCodes.add("UGX");
            isoCodes.add("ZAR");
            isoCodes.add("MXV");
            isoCodes.add("TND");
            isoCodes.add("CUC");
            isoCodes.add("BSD");
            isoCodes.add("SLL");
            isoCodes.add("SDG");
            isoCodes.add("IQD");
            isoCodes.add("GMD");
            isoCodes.add("CUP");
            isoCodes.add("TWD");
            isoCodes.add("RSD");
            isoCodes.add("DOP");
            isoCodes.add("KMF");
            isoCodes.add("MYR");
            isoCodes.add("FKP");
            isoCodes.add("XOF");
            isoCodes.add("GEL");
            isoCodes.add("UYU");
            isoCodes.add("MAD");
            isoCodes.add("CVE");
            isoCodes.add("TOP");
            isoCodes.add("AZN");
            isoCodes.add("OMR");
            isoCodes.add("PGK");
            isoCodes.add("KES");
            isoCodes.add("SEK");
            isoCodes.add("BTN");
            isoCodes.add("UAH");
            isoCodes.add("GNF");
            isoCodes.add("ERN");
            isoCodes.add("MZN");
            isoCodes.add("SVC");
            isoCodes.add("ARS");
            isoCodes.add("QAR");
            isoCodes.add("IRR");
            isoCodes.add("MRO");
            isoCodes.add("CNY");
            isoCodes.add("XPF");
            isoCodes.add("THB");
            isoCodes.add("UZS");
            isoCodes.add("BDT");
            isoCodes.add("LYD");
            isoCodes.add("BMD");
            isoCodes.add("KWD");
            isoCodes.add("PHP");
            isoCodes.add("RUB");
            isoCodes.add("PYG");
            isoCodes.add("ISK");
            isoCodes.add("JMD");
            isoCodes.add("COP");
            isoCodes.add("USD");
            isoCodes.add("MKD");
            isoCodes.add("COU");
            isoCodes.add("DZD");
            isoCodes.add("PAB");
            isoCodes.add("SGD");
            isoCodes.add("ETB");
            isoCodes.add("KGS");
            isoCodes.add("SOS");
            isoCodes.add("VUV");
            isoCodes.add("VEF");
            isoCodes.add("LAK");
            isoCodes.add("BND");
            isoCodes.add("XAF");
            isoCodes.add("LRD");
            isoCodes.add("HRK");
            isoCodes.add("CHF");
            isoCodes.add("DJF");
            isoCodes.add("ZMW");
            isoCodes.add("TZS");
            isoCodes.add("VND");
            isoCodes.add("AUD");
            isoCodes.add("ILS");
            isoCodes.add("GHS");
            isoCodes.add("GYD");
            isoCodes.add("KPW");
            isoCodes.add("CHW");
            isoCodes.add("BOB");
            isoCodes.add("KHR");
            isoCodes.add("MDL");
            isoCodes.add("IDR");
            isoCodes.add("KYD");
            isoCodes.add("AMD");
            isoCodes.add("BWP");
            isoCodes.add("SHP");
            isoCodes.add("TRY");
            isoCodes.add("LBP");
            isoCodes.add("TJS");
            isoCodes.add("JOD");
            isoCodes.add("HKD");
            isoCodes.add("RWF");
            isoCodes.add("AED");
            isoCodes.add("EUR");
            isoCodes.add("LSL");
            isoCodes.add("DKK");
            isoCodes.add("CAD");
            isoCodes.add("BOV");
            isoCodes.add("BGN");
            isoCodes.add("MMK");
            isoCodes.add("NOK");
            isoCodes.add("MUR");
            isoCodes.add("SYP");
            isoCodes.add("ZWL");
            isoCodes.add("GIP");
            isoCodes.add("RON");
            isoCodes.add("LKR");
            isoCodes.add("NGN");
            isoCodes.add("CRC");
            isoCodes.add("CZK");
            isoCodes.add("PKR");
            isoCodes.add("XCD");
            isoCodes.add("HTG");
            isoCodes.add("XSU");
            isoCodes.add("BHD");
            isoCodes.add("KZT");
            isoCodes.add("SRD");
            isoCodes.add("SZL");
            isoCodes.add("SAR");
            isoCodes.add("TTD");
            isoCodes.add("YER");
            isoCodes.add("MVR");
            isoCodes.add("INR");
            isoCodes.add("AWG");
            isoCodes.add("KRW");
            isoCodes.add("NPR");
            isoCodes.add("JPY");
            isoCodes.add("MNT");
            isoCodes.add("AOA");
            isoCodes.add("PLN");
            isoCodes.add("GBP");
            isoCodes.add("SBD");
            isoCodes.add("HUF");
            isoCodes.add("BYR");
            isoCodes.add("BIF");
            isoCodes.add("MWK");
            isoCodes.add("MGA");
            isoCodes.add("BZD");
            isoCodes.add("BAM");
            isoCodes.add("MOP");
            isoCodes.add("EGP");
            isoCodes.add("NAD");
            isoCodes.add("SSP");
            isoCodes.add("NIO");
            isoCodes.add("PEN");
            isoCodes.add("NZD");
            isoCodes.add("WST");
            isoCodes.add("TMT");
            isoCodes.add("CLF");
            isoCodes.add("BRL");
        } catch (Exception e) {
            throw new ClassCastException("Must initialize \"Currencies\" with .init() before usage.");
        }
    }

    private static void addCurrenciesToIsoToName() {
        try {
            isoToName.put("AFN", "Afghani");
            isoToName.put("FJD", "Fiji Dollar");
            isoToName.put("MXN", "Mexican Peso");
            isoToName.put("STD", "Dobra");
            isoToName.put("SCR", "Seychelles Rupee");
            isoToName.put("CDF", "Congolese Franc");
            isoToName.put("BBD", "Barbados Dollar");
            isoToName.put("GTQ", "Quetzal");
            isoToName.put("CLP", "Chilean Peso");
            isoToName.put("HNL", "Lempira");
            isoToName.put("UGX", "Uganda Shilling");
            isoToName.put("ZAR", "Rand");
            isoToName.put("MXV", "Mexican Unidad de Inversion (UDI)");
            isoToName.put("TND", "Tunisian Dinar");
            isoToName.put("CUC", "Peso Convertible");
            isoToName.put("BSD", "Bahama Dollar");
            isoToName.put("SLL", "Leone");
            isoToName.put("SDG", "Sudanese Pound");
            isoToName.put("IQD", "Iraqi Dinar");
            isoToName.put("GMD", "Dalasi");
            isoToName.put("CUP", "Cuban Peso");
            isoToName.put("TWD", "New Taiwan Dollar");
            isoToName.put("RSD", "Serbian dinar");
            isoToName.put("DOP", "Dominican peso");
            isoToName.put("KMF", "Comoro Franc");
            isoToName.put("MYR", "Malaysian Ringgit");
            isoToName.put("FKP", "Falkland Islands Pound");
            isoToName.put("XOF", "CFA Franc BCEAO");
            isoToName.put("GEL", "Lari");
            isoToName.put("UYU", "Peso Uruguayo");
            isoToName.put("MAD", "Moroccan Dirham");
            isoToName.put("CVE", "Cape Verde Escudo");
            isoToName.put("TOP", "Pa'anga");
            isoToName.put("AZN", "Azerbaijani Manat");
            isoToName.put("OMR", "Rial Omani");
            isoToName.put("PGK", "Kina");
            isoToName.put("KES", "Kenya Shilling");
            isoToName.put("SEK", "Swedish Krona");
            isoToName.put("BTN", "Ngultrum");
            isoToName.put("UAH", "Hryvnia");
            isoToName.put("GNF", "Guinea Franc");
            isoToName.put("ERN", "Nakfa");
            isoToName.put("MZN", "Mozambique Metical");
            isoToName.put("SVC", "El Salvador Colon");
            isoToName.put("ARS", "Argentine Peso");
            isoToName.put("QAR", "Qatar Riyal");
            isoToName.put("IRR", "Iranian Rial");
            isoToName.put("MRO", "Ouguiya");
            isoToName.put("CNY", "Yuan Renminbi");
            isoToName.put("XPF", "CFP Franc");
            isoToName.put("THB", "Baht");
            isoToName.put("UZS", "Soʻm");
            isoToName.put("BDT", "Taka");
            isoToName.put("LYD", "Libyan Dinar");
            isoToName.put("BMD", "Bermudian Dollar");
            isoToName.put("KWD", "Kuwaiti dinar");
            isoToName.put("PHP", "Philippine Peso");
            isoToName.put("RUB", "Russian rouble");
            isoToName.put("PYG", "Guarani");
            isoToName.put("ISK", "Icelandic Krona");
            isoToName.put("JMD", "Jamaican dollar");
            isoToName.put("COP", "Colombian peso");
            isoToName.put("USD", "US Dollar");
            isoToName.put("MKD", "Denar");
            isoToName.put("COU", "Unidad de Valor Real");
            isoToName.put("DZD", "Algerian Dinar");
            isoToName.put("PAB", "Balboa");
            isoToName.put("SGD", "Singapore dollar");
            isoToName.put("ETB", "Ethiopian Birr");
            isoToName.put("KGS", "Som");
            isoToName.put("SOS", "Somali Shilling");
            isoToName.put("VUV", "Vatu");
            isoToName.put("VEF", "Bolivar");
            isoToName.put("LAK", "Kip");
            isoToName.put("BND", "Brunei Dollar");
            isoToName.put("XAF", "CFA Franc BEAC");
            isoToName.put("LRD", "Liberian Dollar");
            isoToName.put("HRK", "Kuna");
            isoToName.put("CHF", "Swiss Franc");
            isoToName.put("DJF", "Djibouti Franc");
            isoToName.put("ZMW", "Zambian Kwacha");
            isoToName.put("TZS", "Tanzanian Shilling");
            isoToName.put("VND", "Dong");
            isoToName.put("AUD", "Australian dollar");
            isoToName.put("ILS", "New Israeli Shekel");
            isoToName.put("GHS", "Ghana Cedi");
            isoToName.put("GYD", "Guyana Dollar");
            isoToName.put("KPW", "North Korean Won");
            isoToName.put("CHW", "WE Franc");
            isoToName.put("BOB", "Boliviano");
            isoToName.put("CHR", "Riel");
            isoToName.put("MDL", "Moldovan Leu");
            isoToName.put("IDR", "Rupiah");
            isoToName.put("KYD", "Cayman Islands Dollar");
            isoToName.put("AMD", "Armenian dram");
            isoToName.put("BWP", "Pula");
            isoToName.put("SHP", "St Helena Pound");
            isoToName.put("TRY", "Turkish Lira");
            isoToName.put("LBP", "Lebanese Pound");
            isoToName.put("TJS", "Somoni");
            isoToName.put("JOD", "Jordanian Dinar");
            isoToName.put("HKD", "Hong Kong Dollar");
            isoToName.put("RWF", "Rwanda Franc");
            isoToName.put("AED", "UAE Dirham");
            isoToName.put("EUR", "Euro");
            isoToName.put("LSL", "Loti");
            isoToName.put("DKK", "Danish Krone");
            isoToName.put("CAD", "Canadian dollar");
            isoToName.put("BOV", "Mvdol");
            isoToName.put("BGN", "Bulgarian Lev");
            isoToName.put("MMK", "Kyat");
            isoToName.put("NOK", "Norwegian Kroner");
            isoToName.put("MUR", "Mauritius Rupee");
            isoToName.put("SYP", "Syrian pound");
            isoToName.put("ZWL", "Zimbabwe Dollar");
            isoToName.put("GIP", "Gibraltar Pound");
            isoToName.put("RON", "Romanian Leu");
            isoToName.put("LKR", "Sri Lanka Rupee");
            isoToName.put("NGN", "Naira");
            isoToName.put("CRC", "Costa Rican Colon");
            isoToName.put("CZK", "Czech Koruna");
            isoToName.put("PKR", "Pakistani Rupee");
            isoToName.put("XCD", "East Caribbean Dollar");
            isoToName.put("HTG", "Gourde");
            isoToName.put("XSU", "Sucre");
            isoToName.put("BHD", "Bahraini Dinar");
            isoToName.put("KZT", "Tenge");
            isoToName.put("SRD", "Surinamese dollar");
            isoToName.put("SZL", "Lilangeni");
            isoToName.put("SAR", "Saudi Riyal");
            isoToName.put("TTD", "Trinidad and Tobago Dollar");
            isoToName.put("YER", "Yemeni Rial");
            isoToName.put("MVR", "Rufiyaa");
            isoToName.put("INR", "Indian Rupee");
            isoToName.put("AWG", "Aruban Florin");
            isoToName.put("KRW", "Won");
            isoToName.put("NPR", "Nepalese Rupee");
            isoToName.put("JPY", "Yen");
            isoToName.put("MNT", "Tugrik");
            isoToName.put("AOA", "Kwanza");
            isoToName.put("PLN", "Zloty");
            isoToName.put("GBP", "Pound Sterling");
            isoToName.put("SBD", "Solomon Islands dollar");
            isoToName.put("HUF", "Forint");
            isoToName.put("BYR", "Belarusian rouble");
            isoToName.put("BIF", "Burundi Franc");
            isoToName.put("MWK", "Kwacha");
            isoToName.put("MGA", "Madagascar Ariary");
            isoToName.put("BZD", "Belize Dollar");
            isoToName.put("BAM", "Convertible Mark");
            isoToName.put("MOP", "Pataca");
            isoToName.put("EGP", "Egyptian Pound");
            isoToName.put("NAD", "Namibian Dollar");
            isoToName.put("SSP", "South Sudanese Pound");
            isoToName.put("NIO", "Cordoba Oro");
            isoToName.put("PEN", "Nuevo Sol");
            isoToName.put("NZD", "New Zealand Dollar");
            isoToName.put("WST", "Tala");
            isoToName.put("TMT", "Turkmenistan Manat");
            isoToName.put("CLF", "Unidad de Fomento");
            isoToName.put("BRL", "Brazilian Real");
        } catch (Exception e) {
            throw new ClassCastException("Must initialize \"Currencies\" with .init() before usage.");
        }
    }

}
